---
- name: Test Playbook fot Patching Report
  hosts: all
  gather_facts: False
  
  tasks:
  - name: Run uname command to capture kernel version
    shell: pwd;ls; df; ls -l /mnt
    delegate_to: localhost
    register: out1

  - name: copy to file
    lineinfile:
      path: /runner/project/playbook/output.txt
      line: "{{ out1.stdout }}"
      create: yes
    delegate_to: localhost
