---
- name: Test Playbook fot Patching Report
  hosts: all
  gather_facts: False
  
  tasks:
  - name: Run uname command to capture kernel version
    shell: id -a;ls; df; ls -l /mnt; ls -l /mnt/data
    delegate_to: localhost
    register: out1

  - name: copy to file
    lineinfile:
      path: /mnt/data/job_output.txt
      line: "{{ out1.stdout }}"
      create: yes
    delegate_to: localhost
